### PR TITLE
Implement StatusBar Menu

### PR DESCRIPTION
**Pull request by Itaybre**
Implements #6

### CODE REVIEW

**Comment by ckolderup** [comment]
@Itaybre is there a reason this didn't get merged? I would love to keep the app open but not have it take up a spot in my Dock.

**Comment by Itaybre** [comment]
@ckolderup stalest closed it, I wanted to add more features to the statusbar before merging this change

**Comment by mattheworiordan** [comment]
Any update on this?

**Comment by Itaybre** [comment]
As I said in #72, I have been busy with my thesis, but once I complete it I plan to finish these PRs that are just missing a couple of details

**Comment by mattheworiordan** [comment]
> As I said in https://github.com/Itaybre/CameraController/issues/72,

Sorry, didn't see that one.

Good luck with the thesis 🤞

**Pull request merged**
